### ISSUE TITLE
Stack tags on creation

### ISSUE THREAD

**Issue by herebebogans** [ampedandwired/bora#22]
There's currently no support for creating tag / value pairs for the CF stack itself?

Thoughts on extending the yaml to something like.

```
templates:
  mystack:
    template_file: mystack.rb
    stacks:
      tags:
        - Name: Name
          Value: My application stack
      uat:
        tags:
          - Name: Environment
            Value: uat
          - Name: Cost_Center
            Value: Development
        params:
          InstanceType: t2.micro
      prod:
        tags:
          - Name: Environment
            Value: prod
          - Name: Cost_Center
            Value: Business
        params:
          InstanceType: m4.xlarge
```

The tags would then be passed to the create_stack / update_stack api.

**Comment by ampedandwired** [comment]
That's correct, tagging the actual stack is not implemented yet, but it's a good idea. What do you think about simplifying the yaml syntax a bit like this?

```yaml
templates:
  mystack:
    template_file: mystack.rb
    stacks:
      tags:
        - Name: Name
          Value: My application stack
      uat:
        tags:
          Environment: uat
          Cost_Center: Development
        params:
          InstanceType: t2.micro
      prod:
        tags:
          Environment: prod
          Cost_Center: Business
        params:
          InstanceType: m4.xlarge
```
