### ISSUE TITLE
Allow params to refer to other params in substitutions

### ISSUE THREAD

**Issue by ampedandwired** [ampedandwired/bora#8]
It would be great if you could do this:
```yaml
params:
  domain: example.com
  url: http://${domain}/foo
```
