### ISSUE TITLE
Parameter substitutions should handle arrays and hashes

### ISSUE THREAD

**Issue by ampedandwired** [ampedandwired/bora#9]
Presently substitutions only happen on top-level values. Ideally it should work for values that are inside a hash or array as well, like this:

```yaml
params:
  users:
    - username: bill
      password: ${credstash:///bill_password}
```
